### ISSUE TITLE
How to add buttons

### ISSUE THREAD

**Issue by DClarke1989** [freaktechnik/flic-button-adapter#4]
I'm having difficulty setting up my Flic button using this adapter.

I have a Raspberry Pi Zero W running my gateway and can pair my Flic buttons using the SimpleClient within the Flic SDK, so I don't have any hardware issues.

Can you add to the README to describe how to actually add buttons?
Do I need to do this within the SDK itself, or does your code include this process?

A step-by-step guide for beginners like me would be really helpful

**Comment by freaktechnik** [comment]
You pair them from the gateway pairing screen/device discovery screen, after going to that screen push your button once. As one of the descriptions of the adapter says, you may have to unpair your button first by pressing it for 5 seconds.
