### ISSUE TITLE
Flic2 support

### ISSUE THREAD

**Issue by tim-hellhake** [freaktechnik/flic-button-adapter#5]
There is a new release of the `fliclib-linux-hci` lib with Flic2 support.
See https://github.com/50ButtonsEach/fliclib-linux-hci/commits/master.

**Comment by freaktechnik** [comment]
Huh, I thought they claimed flic 2 would use an "all new" "open" protocol...

**Comment by tim-hellhake** [comment]
They have new SDKs for the flic2 but only for android and ios.
I couldn't find a specification of the protocol itself.
But I thought it makes more sense to update this addon rather than creating a new add-on for the flic2.
I guess they implemented the new protocol in the binary.

**Comment by mrstegeman** [comment]
f2438f4db05dfb4f4f6341aac21eccc8561370e5

I'm waiting on mine to arrive to test.

**Comment by mrstegeman** [comment]
By the way, they _did_ document the protocol here: https://github.com/50ButtonsEach/flic2-documentation/wiki/Flic-2-Protocol-Specification

However, I assume it only applies to the Flic 2, so it makes sense to just stick with the binary approach this adapter uses.

**Comment by ghost** [comment]
Thank you for flic2 support! 
Do you know when this version is available on Mozilla WebThings gateway >> add-ons >>new addon?

Right now I see the flic button add-on but, its a version behind this one ( showing 0.2.0). Thanks for the information!

**Comment by mrstegeman** [comment]
I someone (you, @tim-hellhake, @freaktechnik) wants to test this and see if it works, that'd be great. Otherwise, I need to wait for my button to arrive from Sweden sometime in the next couple weeks.

**Comment by tim-hellhake** [comment]
I can test it but I guess i have to use a custom build of the gateway with the new service binary?

**Comment by mrstegeman** [comment]
Not the gateway, just the add-on. The binary is in the add-on.

**Comment by ghost** [comment]
Just wanted to thank the Mozilla team here for all the amazing products you build and impact to open source community - its had a huge impact on many people's careers (including mine).

**Comment by mrstegeman** [comment]
@PaulFish-Radius Thanks 😄

**Comment by mrstegeman** [comment]
Ok, this seems to work. I've released v0.3.0.

**Comment by ghost** [comment]
Works great @mrstegeman ty
